## NumPy Arithmetic

### Scalar Arithmetic
A scalar is a single number. When you apply an operation to an array with a scalar,
it applies to **every element** automatically — no loops needed.

| Operation | Symbol | Example |
|-----------|--------|---------|
| Addition | `+` | `array + 1` |
| Subtraction | `-` | `array - 2` |
| Multiplication | `*` | `array * 3` |
| Division | `/` | `array / 4` |
| Power | `**` | `array ** 5` |


In [6]:
import numpy as np

# Scaler arithmetic

array = np.array([1, 2, 3])
print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array ** 5)


[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


### Vectorized Math Functions
NumPy has built-in math functions that work on entire arrays at once.

| Function | Meaning |
|----------|---------|
| `np.sqrt(array)` | square root of each element |
| `np.round(array)` | round each element |
| `np.floor(array)` | round down each element |
| `np.ceil(array)` | round up each element |
| `np.pi` | returns the value of π (3.14159...) |

In [7]:
import numpy as np 

# Vectorized math funcs

array = np.array([1.01, 2.5, 3.99])
print(np.sqrt(array))
print(np.round(array))
print(np.floor(array))
print(np.ceil(array))
print(np.pi)

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]
3.141592653589793


### Exercise — Area of a Circle
Formula: π × r²
```python
np.pi * radii**2
```
NumPy calculates the area for every radius in the array at once.

In [8]:
import numpy as np 

# Exercise

radii = np.array([1, 2, 3])
print(np.pi * radii**2) 

[ 3.14159265 12.56637061 28.27433388]


### Element-wise Arithmetic
When you do arithmetic between two arrays of the **same size**,
NumPy operates on matching elements — index 0 with index 0, index 1 with index 1, and so on.

| Operation | Example |
|-----------|---------|
| Addition | `array1 + array2` |
| Subtraction | `array2 - array1` |
| Multiplication | `array1 * array2` |
| Division | `array1 / array2` |
| Power | `array2 ** array1` |

In [9]:
import numpy as np 

# Element wise arithmetic

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array2 - array1)
print(array1 * array2)
print(array1 / array2)
print(array2 ** array1)

[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  4  25 216]


### Comparison Operators
You can compare an array against a value — returns a **boolean array** of True/False.

```python
scores == 100   # which elements equal 100?
scores >= 70    # which elements are passing?
```

You can also use the boolean result to **modify** elements:
```python
scores[scores < 70] = 0   # set all failing scores to 0
```
This is called **boolean indexing** — very powerful and used a lot in ML.

In [10]:
import numpy as np 

# Comparison operators

scores = np.array([91, 55, 100, 73, 82, 64])

print(scores == 100) #Check if anyone got 100
print(scores >= 70) #Check passsing students

scores[scores < 70] = 0
print(scores)

[False False  True False False False]
[ True False  True  True  True False]
[ 91   0 100  73  82   0]
