In [1]:
import numpy as np

# Scaler arithmetic

array = np.array([1, 2, 3])
print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array ** 5)


[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [ ]:
import numpy as np 

# Vectorized math funcs

array = np.array([1.01, 2.5, 3.99])
print(np.sqrt(array))
print(np.round(array))
print(np.floor(array))
print(np.ceil(array))
print(np.pi) #returns pi

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]


In [ ]:
import numpy as np 

# Exercise

radii = np.array([1, 2, 3])
print(np.pi * radii**2) #area of a circle

[ 3.14159265 12.56637061 28.27433388]


In [6]:
import numpy as np 

# Element wise arithmetic

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array2 - array1)
print(array1 * array2)
print(array1 / array2)
print(array2 ** array1)

[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  4  25 216]


In [9]:
import numpy as np 

# Comparison operators

scores = np.array([91, 55, 100, 73, 82, 64])

print(scores == 100) #Check if anyone got 100
print(scores >= 70) #Check passsing students

scores[scores < 70] = 0
print(scores)

[False False  True False False False]
[ True False  True  True  True False]
[ 91   0 100  73  82   0]
