## NumPy Broadcasting

### What is Broadcasting?
Broadcasting is NumPy's way of performing arithmetic on arrays of **different shapes**.
Instead of requiring both arrays to be the same size, NumPy automatically "stretches"
the smaller array to match the larger one.

### How it Works
NumPy compares the shapes of two arrays from right to left.
A dimension is compatible if:
- They are equal, **or**
- One of them is 1

### Example 1 — (1,4) × (4,1)
```python
array1.shape = (1, 4)  # 1 row, 4 columns  → [1, 2, 3, 4]
array2.shape = (4, 1)  # 4 rows, 1 column  → [[1],[2],[3],[4]]
```
Result shape: **(4, 4)** — each element of array1 multiplied by each element of array2.
Produces a multiplication table.

### Example 2 — (4,4) × (4,1)
```python
array1.shape = (4, 4)  # full 4x4 grid
array2.shape = (4, 1)  # single column
```
Result shape: **(4, 4)** — each row of array1 gets multiplied by the matching scalar in array2.

### Example 3 — (1,10) × (10,1)
```python
array1.shape = (1, 10)   # 1 row, 10 columns
array2.shape = (10, 1)   # 10 rows, 1 column
```
Result shape: **(10, 10)** — produces a full 10×10 multiplication table.

### Key Rule
| array1 shape | array2 shape | result shape |
|-------------|-------------|-------------|
| (1, 4) | (4, 1) | (4, 4) |
| (4, 4) | (4, 1) | (4, 4) |
| (1, 10) | (10, 1) | (10, 10) |

### Why Broadcasting Matters in ML
Broadcasting is used constantly in ML for:
- Scaling features in a dataset
- Computing distances between points
- Applying weights to neural network layers

No loops needed — NumPy handles it all automatically and much faster.

In [11]:
import numpy as np

array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)
print(array2.shape)

print(array1*array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [12]:
import numpy as np

array1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)
print(array2.shape)

print(array1*array2)

(4, 4)
(4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [13]:
import numpy as np

array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

print(array1.shape)
print(array2.shape)

print(array1*array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
