


## Filtering

Filtering lets you select elements from an array that meet a specific condition using **boolean indexing**.

- Returns a **1D array** of values that satisfy the condition
- Uses comparison operators: `<`, `>`, `<=`, `>=`, `==`, `!=`
- Combine conditions with `&` (and), `|` (or), `~` (not)

---

### Boolean Indexing (1D Arrays)

| Code | Meaning |
|------|---------|
| `array[array > 10]` | all elements greater than 10 |
| `array[array == 5]` | all elements equal to 5 |
| `array[array != 0]` | all non-zero elements |
| `array[array % 2 == 0]` | all even numbers |
| `array[(array >= 10) & (array <= 20)]` | all elements between 10 and 20 |
| `array[(array < 5) \| (array > 50)]` | all elements less than 5 OR greater than 50 |
| `array[~(array > 10)]` | all elements NOT greater than 10 (≤ 10) |

---

### Boolean Indexing (2D Arrays)

| Code | Meaning |
|------|---------|
| `array[array > 50]` | all elements > 50 (returns flattened 1D) |
| `array[0, array[0] > 10]` | filter row 0 by condition |
| `array[:, 1][array[:, 1] > 10]` | filter column 1 by condition |

---

### Multiple Conditions

Use `&` (and), `|` (or), and `~` (not). **Always wrap conditions in parentheses.**

| Code | Meaning |
|------|---------|
| `(array >= 18) & (array < 65)` | adults (18 to 64) |
| `(array < 13) | (array >= 65)` | children OR seniors |
| `~ (array == 0)` | all elements that are not zero |
| `(array > 10) & (array < 20) & (array % 2 == 0)` | even numbers between 10 and 20 |

---

### np.where()

`np.where(condition, value_if_true, value_if_false)` — returns an array of the **same shape**.

| Code | Meaning |
|------|---------|
| `np.where(array > 0, array, 0)` | replace negatives with 0, keep positives |
| `np.where(array >= 18, array, 0)` | keep adults, set minors to 0 |
| `np.where(array % 2 == 0, "even", "odd")` | label even/odd elements |
| `np.where(array == 0)` | returns **indices** where condition is True |

---

### Common Filtering Functions

| Function | Meaning |
|----------|---------|
| `np.extract(condition, array)` | same as boolean indexing, returns 1D |
| `np.argwhere(array > 10)` | indices of elements that match condition |
| `np.nonzero(array)` | indices of all non-zero elements |
| `np.isin(array, [1, 2, 3])` | True where element is in the list `[1, 2, 3]` |
| `np.any(array > 100)` | `True` if **any** element matches |
| `np.all(array > 0)` | `True` if **all** elements match |

---

### Key Rules

1. **Boolean indexing always flattens** — `array[array > 10]` returns a 1D array even if `array` is 2D.
2. **`&` and `|` not `and` / `or`** — use bitwise operators for element-wise conditions.
3. **Parentheses are required** — `(array > 10) & (array < 20)` not `array > 10 & array < 20`.
4. **`np.where` preserves shape** — it returns an array with the same dimensions as the input.
5. **`~` inverts the condition** — `~(array > 10)` is the same as `array <= 10`.

---


In [16]:
import numpy as np

ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65], 
                 [39, 22, 15, 99, 18, 19, 20, 21]])

# Boolean indexing — returns 1D array of matches

teenagers = ages[ages < 18]
adults = ages[(ages >= 18) & (ages < 65)]
seniors = ages[ages >= 65]
even = ages[ages % 2 == 0]
odd = ages[ages % 2 != 0]
reverse = ages[~(ages<20)]

print(teenagers)
print(adults)
print(seniors)
print(even)
print(odd)
print(reverse)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]
[21 20 30 65 39 22 99 20 21]


In [17]:
import numpy as np

ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65], 
                 [39, 22, 15, 99, 18, 19, 20, 21]])

# np.where — preserves original shape


adults = np.where(ages >= 18, ages, 0)

print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]
