In [9]:
import numpy as np

rng = np.random.default_rng()

print(rng.integers(1,7))
print(rng.integers(low = 1,high = 101, size = 3))
print(rng.integers(low = 1,high = 101, size = (3,2)))



6
[89 76 90]
[[41 34]
 [30 33]
 [61 20]]


In [11]:
import numpy as np

rng = np.random.default_rng(seed=1)

print(rng.integers(low = 1,high = 101, size = (3,2)))


[[48 52]
 [76 96]
 [ 4 15]]
