In [9]:
import numpy as np

rng = np.random.default_rng()

print(rng.integers(1,7))
print(rng.integers(low = 1,high = 101, size = 3))
print(rng.integers(low = 1,high = 101, size = (3,2)))



6
[89 76 90]
[[41 34]
 [30 33]
 [61 20]]


In [11]:
import numpy as np

rng = np.random.default_rng(seed=1)

print(rng.integers(low = 1,high = 101, size = (3,2)))


[[48 52]
 [76 96]
 [ 4 15]]


In [ ]:
import numpy as np

print(np.random.uniform())
print(np.random.uniform(low=-1, high=1, size=3))
print(np.random.uniform(low=-1, high=1, size=(3, 2)))

0.6549438562388386
[-0.44607958 -0.12463733  0.9495509 ]
[[ 0.56967649 -0.79461916]
 [-0.99316423 -0.88461287]
 [ 0.34724311  0.13120951]]


In [15]:
import numpy as np

np.random.seed(seed=1)

print(np.random.uniform(low=-1, high=1, size=(3, 2)))

[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


In [17]:
import numpy as np

rng = np.random.default_rng()

array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)
print(array)

[1 3 5 4 2]


In [26]:
import numpy as np

rng = np.random.default_rng()

fruits = np.array(["🍎", "🍊", "🍌", "🥥", "🍍", "🥝"])
fruits = rng.choice(fruits, size=3)
fruitmat = rng.choice(fruits, size=(3, 3))
print(fruits)
print("")
print(fruitmat)


['🍌' '🥝' '🥥']

[['🥝' '🥝' '🥝']
 ['🥥' '🥝' '🍌']
 ['🥝' '🍌' '🥥']]
