## Creating a Random Generator

```python
import numpy as np

rng = np.random.default_rng()          # new random generator
rng = np.random.default_rng(seed=1)    # with seed for reproducibility
```

## Random Integers — `rng.integers()`

| Code                                             | Meaning                          |
|--------------------------------------------------|----------------------------------|
| `rng.integers(1, 7)`                             | single integer from 1 to **6** (7 is exclusive) |
| `rng.integers(low=1, high=101, size=3)`          | 3 integers from 1 to 100         |
| `rng.integers(low=1, high=101, size=(3, 2))`     | 3×2 matrix of integers 1 to 100  |

> **Note:** `high` is **exclusive** — `integers(1, 7)` gives 1–6, never 7.

## Random Floats — `np.random.uniform()`

| Code                                             | Meaning                          |
|--------------------------------------------------|----------------------------------|
| `np.random.uniform()`                            | single float from 0.0 to 1.0     |
| `np.random.uniform(low=-1, high=1, size=3)`      | 3 floats from -1.0 to 1.0        |
| `np.random.uniform(low=-1, high=1, size=(3, 2))` | 3×2 matrix of floats -1.0 to 1.0 |

## Seeding for Reproducibility

| Code                                             | Meaning                          |
|--------------------------------------------------|----------------------------------|
| `rng = np.random.default_rng(seed=1)`            | same sequence every run          |
| `np.random.seed(seed=1)`                         | same sequence every run          |

## Shuffling an Array — `rng.shuffle()`

| Code                                             | Meaning                          |
|--------------------------------------------------|----------------------------------|
| `rng.shuffle(array)`                             | shuffles the array **in place**  |

```python
array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)
# e.g. [1 3 5 4 2]  — original array is modified
```

> **In-place only** — does not return a new array.

## Random Choice — `rng.choice()`

| Code                                             | Meaning                          |
|--------------------------------------------------|----------------------------------|
| `rng.choice(array, size=3)`                      | pick 3 random items from `array` |
| `rng.choice(array, size=(3, 3))`                 | 3×3 matrix of random picks from `array` |

```python
fruits = np.array(["🍎", "🍊", "🍌", "🥥", "🍐", "🥝"])
fruits   = rng.choice(fruits, size=3)      # e.g. ['🍌' '🥝' '🥥']
fruitmat = rng.choice(fruits, size=(3, 3)) # 3×3 matrix of fruits
```

## Key Rules

1. **`high` is exclusive** for `integers()` — `integers(1, 7)` gives 1–6.
2. **`shuffle` is in-place** — it modifies the original array and returns `None`.
3. **`choice` allows repeats by default**.
4. **Set a `seed`** when you need the same "random" numbers every time.
"""




In [27]:
import numpy as np

rng = np.random.default_rng()

print(rng.integers(1,7))
print(rng.integers(low = 1,high = 101, size = 3))
print(rng.integers(low = 1,high = 101, size = (3,2)))



3
[96 12 80]
[[ 7 30]
 [89 99]
 [69 65]]


In [28]:
import numpy as np

rng = np.random.default_rng(seed=1)

print(rng.integers(low = 1,high = 101, size = (3,2)))


[[48 52]
 [76 96]
 [ 4 15]]


In [29]:
import numpy as np

print(np.random.uniform())
print(np.random.uniform(low=-1, high=1, size=3))
print(np.random.uniform(low=-1, high=1, size=(3, 2)))

0.1862602113776709
[-0.30887855 -0.20646505  0.07763347]
[[-0.16161097  0.370439  ]
 [-0.5910955   0.75623487]
 [-0.94522481  0.34093502]]


In [30]:
import numpy as np

np.random.seed(seed=1)

print(np.random.uniform(low=-1, high=1, size=(3, 2)))

[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


In [31]:
import numpy as np

rng = np.random.default_rng()

array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)
print(array)

[1 4 2 3 5]


In [32]:
import numpy as np

rng = np.random.default_rng()

fruits = np.array(["🍎", "🍊", "🍌", "🥥", "🍍", "🥝"])
fruits = rng.choice(fruits, size=3)
fruitmat = rng.choice(fruits, size=(3, 3))
print(fruits)
print("")
print(fruitmat)


['🥝' '🍍' '🍌']

[['🍍' '🍌' '🍍']
 ['🍍' '🥝' '🥝']
 ['🍌' '🥝' '🍌']]
