## NumPy Array Slicing

### What is Slicing?
Slicing lets you extract a portion of an array using the syntax:
`array[start:end:step]`
- **start** — where to begin (inclusive)
- **end** — where to stop (exclusive)
- **step** — how many elements to skip

### Slicing Rows (1st dimension)
| Code | Meaning |
|------|---------|
| `array[0]` | first row |
| `array[-1]` | last row (negative counts from end) |
| `array[1:3]` | rows 1 and 2 (end is exclusive) |
| `array[0:4:2]` | every 2nd row from 0 to 4 |
| `array[::-1]` | all rows reversed |
| `array[::-2]` | every 2nd row reversed |

### Slicing Columns (2nd dimension)
Use a comma to separate row and column slicing:
`array[rows, columns]`

| Code | Meaning |
|------|---------|
| `array[:, 0]` | first column, all rows |
| `array[:, -1]` | last column, all rows |
| `array[:, 1:]` | all columns from index 1 onwards |
| `array[:, ::2]` | every 2nd column |
| `array[:, ::-2]` | every 2nd column reversed |

### Slicing Both Rows and Columns
You can slice both dimensions at the same time.

| Code | Meaning |
|------|---------|
| `array[0:2, 0:2]` | top left 2x2 block |
| `array[0:2, 2:]` | top right block |
| `array[2:, 0:2]` | bottom left block |
| `array[2:, 2:]` | bottom right block |

### Key Rule
The `:` alone means **all** — so `array[:, 0]` means all rows, column 0.

In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])

# array[start:end:step]
# for rows

print("\n", array[0])
print("\n", array[-1])
print("\n", array[1:3])
print("\n", array[0:4:2]) 
print("\n", array[::-1]) 
print("\n", array[::-2])
 


 [1 2 3 4]

 [13 14 15 16]

 [[ 5  6  7  8]
 [ 9 10 11 12]]

 [[ 1  2  3  4]
 [ 9 10 11 12]]

 [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

 [[13 14 15 16]
 [ 5  6  7  8]]


In [35]:
import numpy as np

array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])

#for column

print("\n", array[:, 0])
print("\n", array[:, -1])
print("\n", array[:, 1:])
print("\n", array[:, ::2])
print("\n", array[:, ::-2])


 [ 1  5  9 13]

 [ 4  8 12 16]

 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]

 [[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]

 [[ 4  2]
 [ 8  6]
 [12 10]
 [16 14]]


In [39]:
import numpy as np

array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])

#for both row and column

print("\n", array[0:2, 0:2])
print("\n", array[0:2, 2:])
print("\n", array[2:, 0:2])
print("\n", array[2:, 2:])



 [[1 2]
 [5 6]]

 [[3 4]
 [7 8]]

 [[ 9 10]
 [13 14]]

 [[11 12]
 [15 16]]
